# pdf_utils.py
import os
import html
from datetime import datetime
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib import colors

# ────────────── Utility ──────────────
def _sanitize(text: str) -> str:
    """Escape HTML characters so ReportLab Paragraph doesn't crash."""
    return html.escape(text)

# ────────────── Footer ──────────────
def _add_footer(canvas, doc):
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawRightString(
        550,
        20,
        f"Page {doc.page} | Generated by SEO Automation System"
    )

# ────────────── Main PDF Function ──────────────
def generate_seo_pdf(pdf_path: str, seo_text: str):
    os.makedirs(os.path.dirname(pdf_path), exist_ok=True)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    # ────────────── Styles ──────────────
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="TitleStyle",
        fontSize=22,
        alignment=TA_CENTER,
        spaceAfter=40,
        leading=28,
        textColor=colors.darkblue,
        bold=True
    ))

    styles.add(ParagraphStyle(
        name="NumberedHeadingStyle",
        fontSize=16,
        textColor=colors.white,
        backColor=colors.darkgreen,
        leftIndent=0,
        spaceBefore=24,
        spaceAfter=12,
        leading=22,
        alignment=TA_LEFT,
        bold=True
    ))

    styles.add(ParagraphStyle(
        name="SubHeadingStyle",
        fontSize=14,
        textColor=colors.darkblue,
        spaceBefore=16,
        spaceAfter=8,
        leading=20,
        leftIndent=12,
        bold=True
    ))

    styles.add(ParagraphStyle(
        name="BodyStyle",
        fontSize=11,
        spaceAfter=12,  # more spacing between paragraphs
        leading=18,      # line height increased
        leftIndent=12
    ))

    styles.add(ParagraphStyle(
        name="MetaStyle",
        fontSize=9,
        textColor=colors.grey,
        alignment=TA_CENTER,
        spaceAfter=30
    ))

    story = []

    # ───────────── Title Page ─────────────
    story.append(Paragraph("Weekly SEO Report", styles["TitleStyle"]))
    story.append(Paragraph(
        f"Generated on: {datetime.now().strftime('%d %B %Y')}",
        styles["MetaStyle"]
    ))

    # ───────────── Directly start content, no extra page break ─────────────
    if not seo_text or not seo_text.strip():
        story.append(Paragraph(
            "⚠️ No SEO insights were generated.",
            styles["BodyStyle"]
        ))
    else:
        heading_colors = [colors.darkgreen, colors.darkred, colors.darkblue, colors.darkorange]
        heading_counter = 0

        for raw_line in seo_text.split("\n"):
            line = raw_line.strip()
            if not line:
                story.append(Spacer(1, 6))  # extra space for empty lines
                continue

            safe_line = _sanitize(line)

            # Numbered Headings
            if safe_line.endswith(":") and len(safe_line) < 60:
                color_index = heading_counter % len(heading_colors)
                heading_color = heading_colors[color_index]

                styles.add(ParagraphStyle(
                    name=f"NumberedHeading{heading_counter}",
                    fontSize=16,
                    textColor=colors.white,
                    backColor=heading_color,
                    leftIndent=0,
                    spaceBefore=18,
                    spaceAfter=10,
                    leading=22,
                    alignment=TA_LEFT,
                    bold=True
                ))

                story.append(Paragraph(f"{heading_counter + 1}. {safe_line}", styles[f"NumberedHeading{heading_counter}"]))
                heading_counter += 1

            # Subheadings (smaller)
            elif safe_line.startswith("###") or safe_line.endswith("**"):
                story.append(Paragraph(safe_line.replace("###", ""), styles["SubHeadingStyle"]))

            # Normal content
            else:
                story.append(Paragraph(safe_line, styles["BodyStyle"]))

    # ───────────── Build PDF ─────────────
    doc.build(story, onFirstPage=_add_footer, onLaterPages=_add_footer)
